### NumPy란?
- **Num**erical **Py**thon의 약자
- 과학 계산을 위한 파이썬 핵심 라이브러리
- 다차원 배열 객체와 다양한 수학 함수 제공

### 왜 NumPy를 사용해야 하는가?
1. **속도**: C로 구현되어 파이썬 리스트보다 10~100배 빠름
2. **메모리 효율**: 연속된 메모리 블록 사용
3. **벡터화 연산**: 반복문 없이 배열 전체 연산 가능
4. **과학 계산 표준**: 대부분의 데이터 분석 라이브러리의 기반

In [1]:
# !pip install numpy

import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 1.26.4


### NumPy vs Python List - 성능 비교

In [2]:
import time

# Python 리스트
size = 1000000
python_list = list(range(size))

start = time.time()
result_list = [x * 2 for x in python_list]
list_time = time.time() - start

# NumPy 배열
numpy_array = np.arange(size)

start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start

print(f"Python 리스트 시간: {list_time:.4f}초")
print(f"NumPy 배열 시간: {numpy_time:.4f}초")
print(f"NumPy가 {list_time/numpy_time:.1f}배 빠름")

Python 리스트 시간: 0.0558초
NumPy 배열 시간: 0.0010초
NumPy가 53.2배 빠름


---
### 배열 생성 및 기본 속성 

In [3]:
# 1. 리스트로부터 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1D 배열:", arr1)

# 2. 2차원 배열
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D 배열:\n", arr2)

# 3. 3차원 배열
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D 배열:\n", arr3)

1D 배열: [1 2 3 4 5]

2D 배열:
 [[1 2 3]
 [4 5 6]]

3D 배열:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# 특수 배열 생성 함수들

# 0으로 채워진 배열
zeros = np.zeros((3, 4))
print("0 배열:\n", zeros)

# 1로 채워진 배열
ones = np.ones((2, 3))
print("\n1 배열:\n", ones)

# 특정 값으로 채워진 배열
full = np.full((2, 2), 7)
print("\n7로 채워진 배열:\n", full)

# 단위 행렬 (Identity matrix)
identity = np.eye(3)
print("\n단위 행렬:\n", identity)

0 배열:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

1 배열:
 [[1. 1. 1.]
 [1. 1. 1.]]

7로 채워진 배열:
 [[7 7]
 [7 7]]

단위 행렬:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 범위 기반 배열 생성

# arange: range와 유사
arr_range = np.arange(0, 10, 2)  # 시작, 끝(미포함), 간격
print("arange:", arr_range)

# linspace: 균등 간격으로 n개 생성
arr_linspace = np.linspace(0, 1, 5)  # 0부터 1까지 5개
print("linspace:", arr_linspace)

# logspace: 로그 스케일
arr_logspace = np.logspace(0, 2, 5)  # 10^0부터 10^2까지 5개
print("logspace:", arr_logspace)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
logspace: [  1.           3.16227766  10.          31.6227766  100.        ]


In [6]:
# 랜덤 배열 생성

# 난수 시드 설정 (재현 가능성)
np.random.seed(42)

# 0~1 사이 균등분포
random_uniform = np.random.random((2, 3))
print("균등분포 난수:\n", random_uniform)

# 정규분포 (평균=0, 표준편차=1)
random_normal = np.random.randn(2, 3)
print("\n정규분포 난수:\n", random_normal)

# 정수 난수 (0~10)
random_int = np.random.randint(0, 10, size=(2, 3))
print("\n정수 난수:\n", random_int)

균등분포 난수:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

정규분포 난수:
 [[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]

정수 난수:
 [[9 5 8]
 [0 9 2]]


### 배열의 기본 속성

In [7]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("배열:\n", arr)
print("\n차원(ndim):", arr.ndim)
print("형태(shape):", arr.shape)  # (행, 열)
print("크기(size):", arr.size)    # 전체 요소 개수
print("데이터 타입(dtype):", arr.dtype)
print("각 요소 크기(itemsize):", arr.itemsize, "bytes")
print("전체 메모리 크기(nbytes):", arr.nbytes, "bytes")

배열:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

차원(ndim): 2
형태(shape): (3, 4)
크기(size): 12
데이터 타입(dtype): int64
각 요소 크기(itemsize): 8 bytes
전체 메모리 크기(nbytes): 96 bytes


### 데이터 타입 (dtype)

In [8]:
# 다양한 데이터 타입

# 정수형
int8_arr = np.array([1, 2, 3], dtype=np.int8)    # -128 ~ 127
int32_arr = np.array([1, 2, 3], dtype=np.int32)  # -2^31 ~ 2^31-1

# 실수형
float32_arr = np.array([1.1, 2.2, 3.3], dtype=np.float32)
float64_arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)  # 기본값

# 불리언
bool_arr = np.array([True, False, True], dtype=np.bool_)

print("int8 메모리:", int8_arr.nbytes, "bytes")
print("int32 메모리:", int32_arr.nbytes, "bytes")
print("float32 메모리:", float32_arr.nbytes, "bytes")
print("float64 메모리:", float64_arr.nbytes, "bytes")

int8 메모리: 3 bytes
int32 메모리: 12 bytes
float32 메모리: 12 bytes
float64 메모리: 24 bytes


In [9]:
# 타입 변환 (astype)
arr_float = np.array([1.7, 2.3, 3.9])
arr_int = arr_float.astype(np.int32)

print("원본(float):", arr_float)
print("변환(int):", arr_int)  # 소수점 버림

원본(float): [1.7 2.3 3.9]
변환(int): [1 2 3]


---
### 배열 인덱싱과 슬라이싱 

### 기본 인덱싱

In [10]:
# 1차원 배열
arr = np.array([10, 20, 30, 40, 50])

print("첫 번째 요소:", arr[0])
print("마지막 요소:", arr[-1])
print("세 번째 요소:", arr[2])

첫 번째 요소: 10
마지막 요소: 50
세 번째 요소: 30


In [11]:
# 2차원 배열
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("배열:\n", arr2d)
print("\n(0, 0) 요소:", arr2d[0, 0])  # 1
print("(1, 2) 요소:", arr2d[1, 2])    # 6
print("첫 번째 행:", arr2d[0])        # [1, 2, 3]
print("두 번째 열:", arr2d[:, 1])     # [2, 5, 8]

배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

(0, 0) 요소: 1
(1, 2) 요소: 6
첫 번째 행: [1 2 3]
두 번째 열: [2 5 8]


### 슬라이싱

In [12]:
# 1차원 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("전체:", arr[:])
print("처음부터 5번째까지:", arr[:5])
print("5번째부터 끝까지:", arr[5:])
print("3번째부터 7번째까지:", arr[3:8])
print("2칸씩 건너뛰기:", arr[::2])
print("역순:", arr[::-1])

전체: [0 1 2 3 4 5 6 7 8 9]
처음부터 5번째까지: [0 1 2 3 4]
5번째부터 끝까지: [5 6 7 8 9]
3번째부터 7번째까지: [3 4 5 6 7]
2칸씩 건너뛰기: [0 2 4 6 8]
역순: [9 8 7 6 5 4 3 2 1 0]


In [13]:
# 2차원 슬라이싱
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

print("원본:\n", arr2d)
print("\n처음 2행, 처음 3열:\n", arr2d[:2, :3])
print("\n모든 행, 2-3열:\n", arr2d[:, 1:3])
print("\n2-3행, 모든 열:\n", arr2d[1:3, :])

원본:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

처음 2행, 처음 3열:
 [[1 2 3]
 [5 6 7]]

모든 행, 2-3열:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

2-3행, 모든 열:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


### 불리언 인덱싱

In [14]:
# 조건을 만족하는 요소만 선택
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 5보다 큰 값들
mask = arr > 5
print("마스크:", mask)
print("5보다 큰 값:", arr[mask])

# 한 줄로 작성
print("짝수:", arr[arr % 2 == 0])
print("3의 배수:", arr[arr % 3 == 0])

마스크: [False False False False False  True  True  True  True  True]
5보다 큰 값: [ 6  7  8  9 10]
짝수: [ 2  4  6  8 10]
3의 배수: [3 6 9]


In [15]:
# 복합 조건 (AND, OR)
arr = np.array([1, 5, 10, 15, 20, 25, 30])

# AND: &
print("10 이상 25 이하:", arr[(arr >= 10) & (arr <= 25)])

# OR: |
print("5 이하 또는 20 이상:", arr[(arr <= 5) | (arr >= 20)])

# NOT: ~
print("10이 아닌 값:", arr[~(arr == 10)])

10 이상 25 이하: [10 15 20 25]
5 이하 또는 20 이상: [ 1  5 20 25 30]
10이 아닌 값: [ 1  5 15 20 25 30]


### 팬시 인덱싱 (Fancy Indexing)

In [16]:
# 정수 배열을 사용한 인덱싱
arr = np.array([10, 20, 30, 40, 50, 60])

# 특정 인덱스의 값들만 선택
indices = np.array([0, 2, 4])
print("선택된 값:", arr[indices])

# 순서를 바꿔서 선택
print("역순 선택:", arr[[5, 3, 1]])

선택된 값: [10 30 50]
역순 선택: [60 40 20]


In [17]:
# 2차원 팬시 인덱싱
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 특정 위치의 요소들 선택
rows = np.array([0, 1, 2])
cols = np.array([0, 1, 2])
print("대각선 요소:", arr2d[rows, cols])  # [1, 5, 9]

대각선 요소: [1 5 9]


---
### 배열 연산 및 브로드캐스팅 

### 기본 산술 연산

In [18]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# 요소별(element-wise) 연산
print("덧셈:", arr1 + arr2)
print("뺄셈:", arr2 - arr1)
print("곱셈:", arr1 * arr2)
print("나눗셈:", arr2 / arr1)
print("거듭제곱:", arr1 ** 2)
print("나머지:", arr2 % arr1)

덧셈: [11 22 33 44]
뺄셈: [ 9 18 27 36]
곱셈: [ 10  40  90 160]
나눗셈: [10. 10. 10. 10.]
거듭제곱: [ 1  4  9 16]
나머지: [0 0 0 0]


In [19]:
# 비교 연산
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("arr1 > arr2:", arr1 > arr2)
print("arr1 == arr2:", arr1 == arr2)
print("arr1 <= 3:", arr1 <= 3)

arr1 > arr2: [False False False  True  True]
arr1 == arr2: [False False  True False False]
arr1 <= 3: [ True  True  True False False]


### 유니버설 함수 (ufunc)

In [20]:
arr = np.array([0, 30, 45, 60, 90])

# 삼각함수 (라디안 단위)
rad = np.deg2rad(arr)  # 도를 라디안으로
print("sin:", np.sin(rad))
print("cos:", np.cos(rad))

# 지수, 로그
arr2 = np.array([1, 2, 3, 4])
print("\nexp:", np.exp(arr2))
print("log:", np.log(arr2))
print("log10:", np.log10(arr2))

# 반올림 함수
arr3 = np.array([1.2, 2.5, 3.7, 4.9])
print("\nround:", np.round(arr3))
print("floor:", np.floor(arr3))
print("ceil:", np.ceil(arr3))

sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

exp: [ 2.71828183  7.3890561  20.08553692 54.59815003]
log: [0.         0.69314718 1.09861229 1.38629436]
log10: [0.         0.30103    0.47712125 0.60205999]

round: [1. 2. 4. 5.]
floor: [1. 2. 3. 4.]
ceil: [2. 3. 4. 5.]


### 브로드캐스팅 (Broadcasting)

In [21]:
# 스칼라와 배열 연산
arr = np.array([1, 2, 3, 4])
print("arr + 10:", arr + 10)  # 모든 요소에 10 더하기
print("arr * 2:", arr * 2)     # 모든 요소에 2 곱하기

arr + 10: [11 12 13 14]
arr * 2: [2 4 6 8]


In [22]:
# 1차원과 2차원 배열 연산
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr1d = np.array([10, 20, 30])

print("2D + 1D:\n", arr2d + arr1d)
# 각 행에 [10, 20, 30]이 더해짐

2D + 1D:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [23]:
# 브로드캐스팅 규칙 시각화
arr_2d = np.ones((3, 4))
arr_1d_col = np.array([[1], [2], [3]])  # (3, 1)
arr_1d_row = np.array([10, 20, 30, 40])  # (4,)

print("arr_2d shape:", arr_2d.shape)
print("arr_1d_col shape:", arr_1d_col.shape)
print("arr_1d_row shape:", arr_1d_row.shape)

print("\n2D + 열 벡터:\n", arr_2d + arr_1d_col)
print("\n2D + 행 벡터:\n", arr_2d + arr_1d_row)

arr_2d shape: (3, 4)
arr_1d_col shape: (3, 1)
arr_1d_row shape: (4,)

2D + 열 벡터:
 [[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]

2D + 행 벡터:
 [[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


### 집계 함수

In [24]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("배열:\n", arr)
print("\n합계:", np.sum(arr))
print("평균:", np.mean(arr))
print("최소값:", np.min(arr))
print("최대값:", np.max(arr))
print("표준편차:", np.std(arr))
print("분산:", np.var(arr))

배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

합계: 45
평균: 5.0
최소값: 1
최대값: 9
표준편차: 2.581988897471611
분산: 6.666666666666667


In [25]:
# 축(axis)을 따른 연산
print("각 열의 합 (axis=0):", np.sum(arr, axis=0))
print("각 행의 합 (axis=1):", np.sum(arr, axis=1))

print("\n각 열의 평균:", np.mean(arr, axis=0))
print("각 행의 최대값:", np.max(arr, axis=1))

각 열의 합 (axis=0): [12 15 18]
각 행의 합 (axis=1): [ 6 15 24]

각 열의 평균: [4. 5. 6.]
각 행의 최대값: [3 6 9]


---
### 배열 형태 변환 및 결합 

### Reshape - 형태 변환

In [26]:
# 1차원 → 2차원
arr = np.arange(12)
print("원본:", arr)

reshaped = arr.reshape(3, 4)
print("\n3x4로 변환:\n", reshaped)

# -1을 사용한 자동 계산
reshaped2 = arr.reshape(4, -1)  # 4행, 열은 자동 계산
print("\n4x3로 변환:\n", reshaped2)

# 3차원으로 변환
reshaped3 = arr.reshape(2, 2, 3)
print("\n2x2x3으로 변환:\n", reshaped3)

원본: [ 0  1  2  3  4  5  6  7  8  9 10 11]

3x4로 변환:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

4x3로 변환:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2x2x3으로 변환:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [27]:
# flatten vs ravel
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# flatten: 복사본 생성
flat = arr2d.flatten()
print("flatten:", flat)

# ravel: 메모리 공유
rav = arr2d.ravel()
print("ravel:", rav)

flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]


### 전치 (Transpose)

In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("원본 (2x3):\n", arr)
print("\n전치 (3x2):\n", arr.T)

# transpose() 함수 사용
print("\ntranspose():\n", np.transpose(arr))

원본 (2x3):
 [[1 2 3]
 [4 5 6]]

전치 (3x2):
 [[1 4]
 [2 5]
 [3 6]]

transpose():
 [[1 4]
 [2 5]
 [3 6]]


### 배열 결합

In [29]:
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# 수직 결합 (vstack)
v_stacked = np.vstack([arr1, arr2])
print("수직 결합:\n", v_stacked)

# 수평 결합 (hstack)
h_stacked = np.hstack([arr1, arr2])
print("\n수평 결합:\n", h_stacked)

수직 결합:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

수평 결합:
 [[1 2 5 6]
 [3 4 7 8]]


In [30]:
# concatenate - 축 지정
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# axis=0: 행 방향 결합
concat_0 = np.concatenate([arr1, arr2], axis=0)
print("axis=0 결합:\n", concat_0)

# axis=1: 열 방향 결합
arr3 = np.array([[7], [8]])
concat_1 = np.concatenate([arr1, arr3], axis=1)
print("\naxis=1 결합:\n", concat_1)

axis=0 결합:
 [[1 2]
 [3 4]
 [5 6]]

axis=1 결합:
 [[1 2 7]
 [3 4 8]]


### 배열 분할

In [ ]:
arr = np.arange(16).reshape(4, 4)
print("원본:\n", arr)

# 수평 분할 (hsplit)
left, right = np.hsplit(arr, 2)
print("\n좌측:\n", left)
print("\n우측:\n", right)

# 수직 분할 (vsplit)
top, bottom = np.vsplit(arr, 2)
print("\n상단:\n", top)
print("\n하단:\n", bottom)

# 위 내용이 혼동된다면...
top, bottom = np.split(arr, 2, axis=0)  
left, right = np.split(arr, 2, axis=1)

원본:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

좌측:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

우측:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

상단:
 [[0 1 2 3]
 [4 5 6 7]]

하단:
 [[ 8  9 10 11]
 [12 13 14 15]]


### 차원 추가/제거

In [32]:
arr = np.array([1, 2, 3, 4])
print("원본 shape:", arr.shape)

# 차원 추가 (newaxis)
arr_col = arr[:, np.newaxis]  # 열 벡터
print("\n열 벡터 shape:", arr_col.shape)
print(arr_col)

arr_row = arr[np.newaxis, :]  # 행 벡터
print("\n행 벡터 shape:", arr_row.shape)
print(arr_row)

원본 shape: (4,)

열 벡터 shape: (4, 1)
[[1]
 [2]
 [3]
 [4]]

행 벡터 shape: (1, 4)
[[1 2 3 4]]


In [33]:
# expand_dims
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)
print("원본 shape:", arr.shape)
print("확장 shape:", expanded.shape)

# squeeze - 크기 1인 차원 제거
arr_squeeze = np.array([[[1], [2], [3]]])
print("\nsqueeze 전:", arr_squeeze.shape)
squeezed = np.squeeze(arr_squeeze)
print("squeeze 후:", squeezed.shape)

원본 shape: (3,)
확장 shape: (1, 3)

squeeze 전: (1, 3, 1)
squeeze 후: (3,)


---
### 통계 및 수학 함수 

### 기본 통계 함수

In [34]:
# 샘플 데이터: 학생 성적
np.random.seed(42)
scores = np.random.randint(50, 100, size=100)

print("평균:", np.mean(scores))
print("중앙값:", np.median(scores))
print("표준편차:", np.std(scores))
print("분산:", np.var(scores))
print("최소값:", np.min(scores))
print("최대값:", np.max(scores))
print("범위:", np.ptp(scores))  # peak to peak

평균: 74.07
중앙값: 73.0
표준편차: 14.375155651331223
분산: 206.6451
최소값: 50
최대값: 99
범위: 49


In [35]:
# 백분위수 (percentile)
print("25 백분위수:", np.percentile(scores, 25))
print("50 백분위수 (중앙값):", np.percentile(scores, 50))
print("75 백분위수:", np.percentile(scores, 75))

# 사분위수
q1, q2, q3 = np.percentile(scores, [25, 50, 75])
iqr = q3 - q1  # 사분위 범위
print(f"\nIQR: {iqr}")

25 백분위수: 63.0
50 백분위수 (중앙값): 73.0
75 백분위수: 88.0

IQR: 25.0


### 정렬

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# sort() : copy sort print(또는 객체명을 type) 해야 결과 볼 수 있음 => 원본 변경
arr_copy = arr.copy()
arr_copy.sort()
print("정렬 (sort):", arr_copy)

# np.sort() : 원본 변경 안됨
sorted_arr = np.sort(arr) 
print("정렬 (np.sort):", sorted_arr)
print("원본:", arr)  # 변경 안됨

# 역순 정렬
print("역순:", np.sort(arr)[::-1])

정렬 (sort): [1 1 2 3 4 5 6 9]
정렬 (np.sort): [1 1 2 3 4 5 6 9]
원본: [3 1 4 1 5 9 2 6]
역순: [9 6 5 4 3 2 1 1]


In [37]:
# argsort - 정렬된 인덱스 반환
arr = np.array([3, 1, 4, 1, 5])
indices = np.argsort(arr)
print("정렬 인덱스:", indices)
print("정렬 결과:", arr[indices])

# 상위 3개 값의 인덱스
top3_indices = np.argsort(arr)[-3:]
print("\n상위 3개 인덱스:", top3_indices)
print("상위 3개 값:", arr[top3_indices])

정렬 인덱스: [1 3 0 2 4]
정렬 결과: [1 1 3 4 5]

상위 3개 인덱스: [0 2 4]
상위 3개 값: [3 4 5]


### 고유값과 빈도

In [38]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# 고유값
unique_vals = np.unique(arr)
print("고유값:", unique_vals)

# 고유값과 개수
values, counts = np.unique(arr, return_counts=True)
print("\n값:", values)
print("개수:", counts)

# 딕셔너리 형태로
freq_dict = dict(zip(values, counts))
print("\n빈도:", freq_dict)

고유값: [1 2 3 4]

값: [1 2 3 4]
개수: [1 2 3 4]

빈도: {1: 1, 2: 2, 3: 3, 4: 4}


### 선형대수 연산

In [39]:
# 행렬 곱셈
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# 요소별 곱셈
print("요소별 곱셈:\n", A * B)

# 행렬 곱셈 (dot product)
print("\n행렬 곱셈 (dot):\n", np.dot(A, B))
print("\n행렬 곱셈 (@):\n", A @ B)

요소별 곱셈:
 [[ 5 12]
 [21 32]]

행렬 곱셈 (dot):
 [[19 22]
 [43 50]]

행렬 곱셈 (@):
 [[19 22]
 [43 50]]


In [40]:
# 행렬식 (determinant)
det = np.linalg.det(A)
print("행렬식:", det)

# 역행렬
A_inv = np.linalg.inv(A)
print("\n역행렬:\n", A_inv)

# 검증: A @ A_inv = I
print("\nA @ A_inv:\n", np.round(A @ A_inv, 10))

행렬식: -2.0000000000000004

역행렬:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv:
 [[1. 0.]
 [0. 1.]]


In [41]:
# 고유값과 고유벡터
A = np.array([[1, 2],
              [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("고유값:", eigenvalues)
print("\n고유벡터:\n", eigenvectors)

고유값: [ 3. -1.]

고유벡터:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [42]:
# 연립방정식 풀기
# 2x + 3y = 8
# 3x + 4y = 11

A = np.array([[2, 3],
              [3, 4]])
b = np.array([8, 11])

x = np.linalg.solve(A, b)
print("해:", x)
print("검증:", A @ x)  # [8, 11]

해: [1. 2.]
검증: [ 8. 11.]
